#!/usr/bin/env python3
"""Generate the Launcher's bounded Simplified Chinese title font."""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_FONT = (
    ROOT
    / "managed_components"
    / "lvgl__lvgl"
    / "scripts"
    / "built_in_font"
    / "SourceHanSansSC-Normal.otf"
)
OUTPUT = ROOT / "assets" / "fonts" / "launcher_source_han_sans_sc_16_gb2312.c"
BROWSER_OUTPUT = ROOT / "tools" / "install-slot" / "title-glyphs.js"
CONVERTER_VERSION = "1.5.3"


def gb2312_level_one_codepoints() -> set[int]:
    """Return the 3,755 common Simplified Chinese characters in GB2312 level one."""
    result: set[int] = set()
    for lead in range(0xB0, 0xD8):
        for trail in range(0xA1, 0xFF):
            try:
                character = bytes((lead, trail)).decode("gb2312")
            except UnicodeDecodeError:
                continue
            result.add(ord(character))
    if len(result) != 3755:
        raise RuntimeError(
            f"expected 3755 GB2312 level-one characters, got {len(result)}"
        )
    return result


def title_codepoints() -> list[int]:
    result = gb2312_level_one_codepoints()
    result.update(range(0x20, 0x7F))
    result.update(range(0x3000, 0x3040))
    result.update(range(0xFF01, 0xFF5F))
    return sorted(result)


def compact_ranges(codepoints: list[int]) -> str:
    ranges: list[str] = []
    start = previous = codepoints[0]
    for codepoint in codepoints[1:]:
        if codepoint == previous + 1:
            previous = codepoint
            continue
        ranges.append(
            f"0x{start:X}" if start == previous else f"0x{start:X}-0x{previous:X}"
        )
        start = previous = codepoint
    ranges.append(
        f"0x{start:X}" if start == previous else f"0x{start:X}-0x{previous:X}"
    )
    return ",".join(ranges)


def write_browser_inventory() -> None:
    characters = "".join(chr(codepoint) for codepoint in sorted(gb2312_level_one_codepoints()))
    BROWSER_OUTPUT.write_text(
        "// Generated by tools/generate_launcher_title_font.py; do not edit.\n"
        f"export const LAUNCHER_GB2312_LEVEL_ONE = {json.dumps(characters, ensure_ascii=False)};\n",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--converter",
        default=shutil.which("lv_font_conv"),
        help=f"path to lv_font_conv {CONVERTER_VERSION}",
    )
    parser.add_argument(
        "--inventory-only",
        action="store_true",
        help="only regenerate the browser-side title glyph inventory",
    )
    args = parser.parse_args()
    write_browser_inventory()
    if args.inventory_only:
        print(BROWSER_OUTPUT)
        return
    if not args.converter:
        parser.error("lv_font_conv was not found; pass --converter")
    if not SOURCE_FONT.is_file():
        parser.error(f"source font is missing: {SOURCE_FONT}")

    version = subprocess.run(
        [args.converter, "--version"],
        check=True,
        capture_output=True,
        text=True,
    ).stdout.strip()
    if CONVERTER_VERSION not in version:
        parser.error(
            f"expected lv_font_conv {CONVERTER_VERSION}, got {version or 'unknown'}"
        )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    subprocess.run(
        [
            args.converter,
            "--font",
            str(SOURCE_FONT),
            "--size",
            "16",
            "--bpp",
            "2",
            "--format",
            "lvgl",
            "--lv-include",
            "lvgl.h",
            "--no-kerning",
            "--range",
            compact_ranges(title_codepoints()),
            "--output",
            str(OUTPUT),
            "--force-fast-kern-format",
            "--lv-font-name",
            "launcher_font_16_gb2312",
        ],
        check=True,
    )
    # Keep generated sources deterministic and clean under git diff --check.
    OUTPUT.write_text(OUTPUT.read_text(encoding="utf-8").rstrip() + "\n",
                      encoding="utf-8")
    print(OUTPUT)
    print(BROWSER_OUTPUT)


if __name__ == "__main__":
    main()
